Feature 13: User can adjust notification volume
solomonjin/final-project pull request #33
Opened 2021-07-30 23:41 UTC by solomonjin

![adjust volume](https://user-images.githubusercontent.com/82540886/127721298-f94fd3d4-717c-4fb9-865e-23a9375c16df.gif)

2021-07-30 23:49 UTC, thebearingedge reviewed
Overall great, but your alignment is starting to look a little random now that there's a lot of stuff on the page.

<img width="690" alt="Screen Shot 2021-07-30 at 4 44 51 PM" src="https://user-images.githubusercontent.com/7432943/127721627-7b87dacd-3d63-48ad-93ae-effccb700315.png">

2021-07-30 23:49 UTC, thebearingedge requested changes
Please see prev comment

2021-07-31 00:16 UTC, solomonjin commented
<img width="290" alt="Screen Shot 2021-07-30 at 5 15 53 PM" src="https://user-images.githubusercontent.com/82540886/127722628-ff35a9d8-a30b-4fbb-81c5-7a54b23adc80.png">
<img width="1032" alt="Screen Shot 2021-07-30 at 5 15 48 PM" src="https://user-images.githubusercontent.com/82540886/127722629-3edb4acd-790f-4e10-bf35-b2df928f802a.png">

2021-07-31 00:17 UTC, thebearingedge approved these changes

2021-07-31 00:18 UTC, merged